### ISSUE TITLE
runtime.client.schedules.list_for_agent() missing + schedules_client() returns a different instance than client.schedules

### ISSUE THREAD

**Issue by shaileshpadave** [agentspan-ai/agentspan#323]
two related schedule surface issues on conductor-python 2.0.0rc2:

1. OrkesSchedulerClient has no list_for_agent() method:

runtime.client.schedules.list_for_agent('my-agent')
# AttributeError: 'OrkesSchedulerClient' object has no attribute 'list_for_agent'

2. runtime.schedules_client() and runtime.client.schedules return different instances — the suite asserts they should be the same object (identity check):

assert runtime.schedules_client() is runtime.client.schedules
# AssertionError — two separate OrkesSchedulerClient objects

both found in suite 24 test_schedule_then_list_then_purge and test_runtime_and_client_share_schedule_client. worked with conductor-python 1.3.11.

**Comment by shaileshpadave** [comment]
closing pending version verification — will reopen or refile if confirmed
